Update Rails to v7.1 (#13267)
* Bump rails to v7.1.x

* Patch application generator

* Successfully generate a Rails 7.1 application

* Patch meetings migrations

* Fix AbstractController::ActionNotFound errors

The show action could not be found for the #<Proc:0x00007e5e587d09a8 decidim-admin/app/controllers/decidim/admin/components/base_controller.rb:26>
  callback on Decidim::Elections::Admin::ElectionsController, but it is listed in the controller's
  :except option.

Raising for missing callback actions is a new default in Rails 7.1, if you'd
  like to turn this off you can delete the option from the environment configurations
  or set `config.action_controller.raise_on_missing_callback_actions` to `false`.

* Use Rails.env.local? instead of Rails.env.test? || Rails.env.development?

* Fix uninitialized constant ActiveRecord::NullRelation Error

* Fix wrong number of arguments (given 1, expected 0) in screenshot_helper.rb

* Fix: cannot load such file -- decidim/action_authorization_helper

* Change repo and branch to decidim default

* Fix: private method `processed?' called for an instance of ActiveStorage::VariantWithRecord

* Fix: nil can't be coerced into Integer

     # /home/runner/work/decidim/decidim/decidim-comments/lib/decidim/comments/engine.rb:43:in `sum'
     # /home/runner/work/decidim/decidim/decidim-comments/lib/decidim/comments/engine.rb:43:in `block (3 levels) in <class:Engine>'
     # /home/runner/work/decidim/decidim/decidim-comments/lib/decidim/comments/engine.rb:42:in `sum'
     # /home/runner/work/decidim/decidim/decidim-comments/lib/decidim/comments/engine.rb:42:in `block (2 levels) in <class:Engine>'
     # ./lib/decidim/stats_registry.rb:55:in `resolve'

* Fix Cannot get a signed_id for a new record

* Fix: expected ActiveSupport::MessageVerifier::InvalidSignature, got #<ActiveSupport::MessageEncryptor::InvalidMessage: mismatched digest> with backtrace:

* Fix: NoMethodError: undefined method `filter_map' for nil

* Fix: JSON::ParserError:  unexpected token at '{ "name": "Organization's name'

* Fix: Blob Matchers

* Fix: SecureRandom received :alphanumeric with unexpected arguments

* Fix: expected to find text "You are being redirected" in ""

* Fix: expected to find text "Puma caught this error: Missing user: invalid_nickname"

* Fix: decidim-generators pipelines

* Fix: undefined method `has_query_constraints?' for class Decidim::UploadValidationForm::AttachmentContextProxy

* Fix: expected to find text "You are being redirected" in ""

* Fix Taxonomy admin routes

* Fix - accountability: No route matches {}, missing required keys: [:component_id, :initiative_slug]

* Fix: ActionController::UrlGenerationError: No route matches {}, missing required keys: [:component_id, :initiative_slug]

* Fix elections pipeline

* Fix queue in decidim-generators

* Fix: undefined method `utc' for an instance of String

* Fix: Translation missing: en.decidim.download_your_data.help.debates.*

* Fix: expected to find text "You are being redirected" in "..."

* Fix - decidim-meetings: ActionController::UrlGenerationError:  No route matches {}, missing required keys: [:component_id, :initiative_slug]

* Fix: ActionController::UnfilteredParameters: unable to convert unpermitted parameters to hash

* Add new Framework defaults file

* Fix: nil can't be coerced into Integer

* Fix: ActionController::InvalidParameterKey:  all keys must be Strings or Symbols, got: Integer

* Fix - decidim-surveys: ActionController::UrlGenerationError: No route matches {:component_id=>1461}, missing required keys: [:initiative_slug]

* Fix: Need Counter Cache with Active Record size: Decidim::Forms::Question => [:display_conditions_for_other_questions]

* Fix spelling - unknown words

* Fix hash issues on initiatives

* Running rubocops

* decidim-generators - patch the logger

* Add information to README

* Markdown Lint

* Apply suggestions from code review

Co-authored-by: Andrés Pereira de Lucena <andreslucena@users.noreply.github.com>

---------

Co-authored-by: Andrés Pereira de Lucena <andreslucena@users.noreply.github.com>